Versioning scheme
lob/lob-openapi pull request #217
Opened 2021-08-20 23:06 UTC by SidneyAllen

Fixes JIRA DXP-104

## Checklist

- [X] Up to date with `main`
- [X] All the tests are passing
  - [X] Prettier
  - [X] Spectral Lint
  - [X] Contract Tests
    - [X] Delete all resources created in contract tests
- [X] `npm run bundle` outputs nothing suspect
- [X] `npm run postman` outputs nothing suspect

## Changes
Expanded the versioning narrative and updated title of spec.

## Areas of Concern (optional)

2021-08-21 00:58 UTC, jho44 commented on Lob-API-public.yml
> +      Lob's API predates our specification and follows [Stripe versioning](https://stripe.com/blog/api-versioning)
```suggestion
      Lob's API predates our specification and follows the [Stripe versioning](https://stripe.com/blog/api-versioning) 
```

2021-08-21 01:02 UTC, jho44 requested changes
smol grammar thing

2021-08-23 17:08 UTC, jho44 approved these changes

2021-08-23 19:04 UTC, sudoku-lord approved these changes

2021-08-23 19:04 UTC, merged