feat(us bulk verify): Add in missing code samples
lob/lob-openapi pull request #309
Opened 2022-02-24 00:27 UTC by Thexumaker

Fixes #\<INSERT ISSUE NUMBER HERE\>

## Checklist

- [ ] Up to date with `main`
- [ ] All the tests are passing
  - [ ] Delete all resources created in tests
- [ ] Prettier
- [ ] Spectral Lint
- [ ] `npm run bundle` outputs nothing suspect
- [ ] `npm run postman` outputs nothing suspect

## Changes
Adds in missing code samples for bulk verify
## Areas of Concern (optional)
Couldn't get tests running locally

2022-02-24 16:04 UTC, sudoku-lord requested changes
It looks like the `bulk_intl_verifications` resource is also missing code samples. Additionally, would it be a good idea to add 2 addresses to the list instead of 1, so it's clearer that this can take in multiple addresses?

2022-02-24 18:12 UTC, Thexumaker commented
> It looks like the `bulk_intl_verifications` resource is also missing code samples. Additionally, would it be a good idea to add 2 addresses to the list instead of 1, so it's clearer that this can take in multiple addresses?

My only thing about adding 2 addresses is that it can get a bit long and I think if the adress is a part of a list data structure it should be clear that you can put multiple addresses. Thoughts?

2022-03-02 04:07 UTC, sudoku-lord commented
The comment about 2 addresses being too long is valid. I think it's fine now.

2022-03-03 02:06 UTC, sudoku-lord approved these changes

2022-03-04 18:36 UTC, merged