Chore: code cleanup
lob/lob-openapi pull request #318
Opened 2022-03-15 16:45 UTC by 1makedadavis

Fixes #\<DXP 806, DXP 808\>

## Checklist

- [x] Up to date with `main`
- [x] All the tests are passing
  - [ ] Delete all resources created in tests
- [x] Prettier
- [x] Spectral Lint
- [x ] `npm run bundle` outputs nothing suspect
- [x] `npm run postman` outputs nothing suspect

## Changes

## Areas of Concern (optional)

2022-03-15 17:13 UTC, SidneyAllen commented
@1makedadavis - can you move swap positions between TypeScript and NodeJ
![Screen Shot 2022-03-15 at 10 12 42 AM](https://user-images.githubusercontent.com/595967/158433779-1e083ca4-f61a-4bac-be3d-db2967ec1fc2.png)
S

2022-03-15 17:17 UTC, SidneyAllen commented
@1makedadavis - Postcard create snippet - we need the addr_xxxx in quotes
![Screen Shot 2022-03-15 at 10 16 25 AM](https://user-images.githubusercontent.com/595967/158434514-b72eb6b4-ce25-4156-8592-44efde368f67.png)

2022-03-15 17:24 UTC, SidneyAllen commented
@mwj8410 and @1makedadavis - I notice in Create Check we type the variable, but other code snippets don't have this.  Can we either remove this or apply it consistently for other create methods?

![Screen Shot 2022-03-15 at 10 22 30 AM](https://user-images.githubusercontent.com/595967/158435772-e017df78-2576-4228-930d-5a2a8065692c.png)

2022-03-15 17:27 UTC, SidneyAllen commented
@1makedadavis - on Verify Bank it looks like the bankData object is unnecessary - I think we should remove it

![Screen Shot 2022-03-15 at 10 25 25 AM](https://user-images.githubusercontent.com/595967/158436252-944771e4-0ffc-4058-8be5-76bdac8ff6ba.png)

2022-03-17 17:18 UTC, mwj8410 requested changes
I went ahead an noted which quotes need to be swapped

2022-03-17 17:18 UTC, mwj8410 commented on resources/bank_accounts/bank_account_verify.yml
> +        lob.BankAccount.verify(id = "bank_dfceb4a2a05b57e", amounts = [25, 63])
should be single quotes in this file

2022-03-17 17:18 UTC, mwj8410 commented on resources/bank_accounts/bank_accounts.yml
> +          "limit" => 2
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/bulk_intl_verifications/bulk_intl_verifications.yml
> +          --data-raw "{
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/bulk_intl_verifications/bulk_intl_verifications.yml
> +              primary_line: "370 Water St",
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/bulk_intl_verifications/bulk_intl_verifications.yml
> +              primary_line: "370 Water St",
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/bulk_us_verifications/bulk_us_verifications.yml
> +          'city'='San Francisco",
ending quote is mismatched

2022-03-17 17:18 UTC, mwj8410 commented on resources/bulk_us_verifications/bulk_us_verifications.yml
> +        $lob->bulkUSVerifications()->verify("addresses" => array(
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/cards/card.yml
> +    #     lob.Card.update("card_7a6d73c5c8457fc")
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/cards/card.yml
> +    #     $lob->cards()->update("card_7a6d73c5c8457fc");
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/cards/cards.yml
> +          "limit" => 2
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/cards/cards.yml
> +          description: "Test card",
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/checks/checks.yml
> +          "limit" => 2
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/checks/checks.yml
> +          --data-urlencode "check_bottom=<h1 style="padding-top:4in;">Demo Check for {{name}}</h1>" \
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/checks/checks.yml
> +        to: {
should read
```
  to: new AddressEditable({
    name: 'Harry Zhang',
    address_line1: '210 King St',
    address_line2: '# 6100',
    address_city: 'San Francisco',
    address_state: 'CA',
    address_zip: '94107',
  }),
```

2022-03-17 17:18 UTC, mwj8410 commented on resources/checks/checks.yml
> +                .setCheckBottom("<h1 style="padding-top:4in;">Demo Check for {{name}}</h1>")
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/checks/checks.yml
> +          check_bottom: "<h1 style="padding-top:4in;">Demo Check for {{name}}</h1>",
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/letters/letters.yml
> +          "limit" => 2
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/letters/letters.yml
> +          --data-urlencode "file=<html style="padding-top: 3in; margin: .5in;">HTML Letter for {{name}}</html>" \
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/letters/letters.yml
> +          file: "<html style="padding-top: 3in; margin: .5in;">HTML Letter for {{name}}</html>",
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/letters/letters.yml
> +                .setFile("<html style="padding-top: 3in; margin: .5in;">HTML Letter for {{name}}</html>")
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/letters/letters.yml
> +          file: "<html style="padding-top: 3in; margin: .5in;">HTML Letter for {{name}}</html>",
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/postcards/postcards.yml
> +          "limit" => 2
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/postcards/postcards.yml
> +          --data-urlencode "front=<html style="padding: 1in; font-size: 50;">Front HTML for {{name}}</html>" \
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/postcards/postcards.yml
> +        to: {
should read
```
to: new AddressEditable({
          name: 'Harry Zhang',
          address_line1: '210 King St',
          address_line2: '# 6100',
          address_city: 'San Francisco',
          address_state: 'CA',
          address_zip: '94107'
        }),

2022-03-17 17:18 UTC, mwj8410 commented on resources/postcards/postcards.yml
> +          front: '<html style="padding: 1in; font-size: 50;">Front HTML for {{name}}</html>'',
has an extra trailing single quote

2022-03-17 17:18 UTC, mwj8410 commented on resources/postcards/postcards.yml
> +          front: "<html style="padding: 1in; font-size: 50;">Front HTML for {{name}}</html>",
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/postcards/postcards.yml
> +          description = "Demo Postcard job",
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/postcards/postcards.yml
> +                .setFront("<html style="padding: 1in; font-size: 50;">Front HTML for {{name}}</html>")
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/postcards/postcards.yml
> +          front: "<html style="padding: 1in; font-size: 50;">Front HTML for {{name}}</html>",
swap outer most double quotes to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/templates/templates.yml
> +          description: 'Newer Template',
swap to single quotes

2022-03-17 17:18 UTC, mwj8410 commented on resources/zip_lookups/zip_lookups.yml
> +          "zip_code" => '94107'
swap to single quotes

2022-03-17 19:36 UTC, mwj8410 approved these changes
Excellent!

2022-03-18 16:48 UTC, merged