[PMAPI-1433] add campaign api resources
lob/lob-openapi pull request #344
Opened 2022-06-22 17:18 UTC by jharrell

Fixes PMAPI-1433

## Checklist

- [x] Up to date with `main`
- [ ] All the tests are passing
  - [ ] Delete all resources created in tests
- [x] Prettier
- [x] Spectral Lint
- [x] `npm run bundle` outputs nothing suspect
- [x] `npm run postman` outputs nothing suspect

## Changes

- adds Campaign, Creative, and Upload routes to our docs.

## Areas of Concern (optional)

- testing, first time contributing.

2022-06-23 22:13 UTC, sudoku-lord requested changes
See comments. I'm particularly curious about why `foobar` is a property in `uploads`. I assume it's a placeholder, but I'd like to know what the intended value is.

2022-06-23 22:13 UTC, sudoku-lord commented on lob-api-public.yml
> +      The API provides endpoints for creating campaigns, updating campaigns, retrieving individual campaigns, and deleting
This specifies that only individual campaigns can be retrieved, but there's an `all_campaigns` model which indicates the presence of a `list` operation. That should be added in.

2022-06-23 22:13 UTC, sudoku-lord commented on resources/campaigns/attributes/cmp_is_draft.yml
> +description: Whether or not the campaign is still a draft.
See my comment in the campaign model: you don't need to extrapolate these attributes into separate files. You can leave them inline.

2022-06-23 22:13 UTC, sudoku-lord commented on resources/campaigns/campaigns.yml
> +  x-codeSamples:
make sure to add in the code samples

2022-06-23 22:13 UTC, sudoku-lord commented on resources/creatives/models/creative_updatable.yml
> +  metadata:
https://github.com/lob/lob-openapi/blob/main/shared/models/metadata.yml

Replace metadata with this (and in any other instances where appropriate).

2022-06-23 22:13 UTC, sudoku-lord commented on resources/creatives/models/creative_writable.yml
> +  metadata:
https://github.com/lob/lob-openapi/blob/main/shared/models/metadata.yml see above comment on metadata.

2022-06-23 22:13 UTC, sudoku-lord commented on resources/uploads/models/uploads.yml
> +  foobar:
the request body property is actually called foobar? or is this a placeholder?

2022-06-24 15:21 UTC, jharrell commented on resources/campaigns/models/campaign.yml
> +        $ref: "../attributes/cmp_is_draft.yml"
done

2022-06-24 17:44 UTC, BennyKitchell commented on resources/campaigns/campaign.yml
> +          # TODO: fill out example
We have a few `Todo's` here. Do we need examples before merging, or is there a specific JIRA task we can include so this doesn't get lost in the shuffle

2022-06-24 17:47 UTC, BennyKitchell commented on resources/campaigns/campaigns.yml
> +          # complete example using all create payload properties
Same question as above, we should either have examples or add a TODO with a JIRA link so it's not lost.

2022-06-24 17:55 UTC, BennyKitchell approved these changes

2022-06-24 18:11 UTC, BennyKitchell commented on resources/campaigns/responses/all_campaigns.yml
> +      data:
Redocly: `example value must conform to the schema "data" property type must be an array`

2022-06-24 18:13 UTC, BennyKitchell commented on resources/campaigns/campaigns.yml
> +          description: "Demo Campaign"
Redocly: `must have required property "name"`

2022-06-24 18:14 UTC, BennyKitchell commented on resources/campaigns/campaigns.yml
> +          # complete example using all create payload properties
Redocly: must have required properties "name" and "schedule_type"

2022-06-24 18:15 UTC, BennyKitchell commented on resources/campaigns/campaigns.yml
> +          description: demo
Redocly: `must have required properties "name" and "schedule_type"`

2022-06-24 18:19 UTC, BennyKitchell commented on resources/creatives/creatives.yml
> +          description: "Demo Creative"
redocly: `Must have required properties "campaign_id" "resource_type" and "details"`

2022-06-24 18:19 UTC, BennyKitchell commented on resources/creatives/creatives.yml
> +          description: encoded demo
redocly: `Must have required properties "campaign_id" "resource_type" and "details"`

2022-06-24 18:19 UTC, BennyKitchell commented on resources/creatives/creatives.yml
> +          description: demo
redocly: `Must have required properties "campaign_id" "resource_type" and "details"`

2022-06-24 18:58 UTC, merged