Pmapi 1829 add buckslips docs
lob/lob-openapi pull request #400
Opened 2022-10-13 00:03 UTC by julielinter

Implements changes for [PMAPI-1829](https://lobsters.atlassian.net/browse/PMAPI-1828)

## Checklist

- [ ] Up to date with `main`
- [ ] All the tests are passing
  - [ ] Delete all resources created in tests
- [x] Prettier
- [x] Spectral Lint
- [x] `npm run bundle` outputs nothing suspect
- [x] `npm run postman` outputs nothing suspect

## Changes
- Adds Buckslip and Buckslip Orders sections under Special Features
- Adds all relevant endpoints to new sections

## Areas of Concern (optional)

2022-10-17 19:55 UTC, jho44 requested changes

2022-10-17 19:55 UTC, jho44 commented on lob-api-public.yml
> +
If you could just move these above the `/bulk/us_verifications` endpoint to maintain the alphabetical ordering, that'd be great ^^

2022-10-17 19:55 UTC, jho44 commented on lob-api-public.yml
> +
LTGM otherwise!

2022-10-19 16:12 UTC, maelingmurphy commented
Just viewed the docs locally using `npm run redoc` and the changes look great, Julie! There have been some inventory-related updates to the Buckslip & Buckslip Order serialized responses ([from this PR](https://github.com/lob/lob-api/pull/8477)) but we can a file a followup ticket for those updates as to not block these initial docs from going out.

2022-10-20 16:29 UTC, jho44 approved these changes
LGTM outside of that thing we talked about with `cards` and `buckslips` not appearing for certified or registered letters. Will also note that you added buckslips to _creatives_, not _campaigns_ (though I know they're part of the same API group...bygones).

2022-10-20 16:32 UTC, merged