GC-446/add-billing-address-required-error
lob/lob-openapi pull request #425
Opened 2023-03-23 18:25 UTC by juanfriss

Fixes [GC-446](https://lobsters.atlassian.net/browse/GC-446)

## Checklist

- [ ] Up to date with `main`
- [ ] All the tests are passing
  - [ ] Delete all resources created in tests
- [ ] Prettier
- [ ] Spectral Lint
- [ ] `npm run bundle` outputs nothing suspect
- [ ] `npm run postman` outputs nothing suspect

2023-03-27 13:49 UTC, shannamurry approved these changes

2023-03-28 18:37 UTC, pop requested changes
@juanfriss in this PR can you please update the [CODEOWNERS](https://github.com/lob/lob-openapi/blob/main/.github/CODEOWNERS) file in this PR to either be either [GCE](https://github.com/orgs/lob/teams/growth-and-core-experience) `@lob/growth-and-core-experience` or [Log Engineering](https://github.com/orgs/lob/teams/engineering) `@lob/engineering` so @BennyKitchell is not a bottleneck to changes to the OpenAPI spec? I can merge the PR once that change is in place. When Benny gets back we can re-assess who should own change to this project.

2023-03-28 20:34 UTC, pop approved these changes

2023-03-28 21:13 UTC, merged

2023-03-29 11:01 UTC, juanfriss commented
@pop anything else we should do? I'm not seeing the new errors in https://docs.lob.com/#tag/Errors